### ISSUE TITLE
Rendering of `@<Fragment 1 @{@<Fragment 2@>...@}@>`

### ISSUE THREAD

**Issue by 5balls** [simonjwright/nuweb.py#10]
Good evening!
This might not be a bug, but if feels a bit like it. When I use the new style "concetanation" argument `@{...@}` ("classic" C nuweb) for example like this
```
@<Fragment 1 @{@<Fragment 2@>...@}@>
```
I get some funny rendering by LaTeX, like this (Spanish style inverse exclamation and question mark and `@`):
```
<Fragment 1 ¡Fragment 2@¿...>
```
I'm currently doing a reimplementation of nuweb in C++ (WIP, I want to make it a LSP Server later) and stumbled on this as I use nuweb now more intensively. It might be difficult to keep track of the different verb / listings environment which could be nested here, but probably `@<` and `@>` should be in a verb environment or replaced by the math mode angle bracket. I currently have only implemented the new style `@'...@'` arguments but this would probably be on the list of things to implement next.
Cheers,
Florian

**Comment by simonjwright** [comment]
It’s seemed to me that the C implementers put in whatever they felt might help their current project without considering whether it was really necessary, and without documenting it, and without sticking to the spirit of LP.

So, I won’t look to implement these "advanced" (read, confusing) features in this project.
