### ISSUE TITLE
@* - undocumented feature or remains of implementation?

### ISSUE THREAD

**Issue by 5balls** [simonjwright/nuweb.py#11]
Good morning!
Going over the unit tests for the C version of nuweb I stumbled upon test 0009 which contains the command "@*" at the end of a scrap. I don't find any documentation about this command, but it seems to ignore the rest of the line (scrap?) till it reads "@}". Is this intended behaviour, is this done for some compability with other web tools or is it some remains of another planned implementation of a command which did not make it? (Maybe some alternative "comment" command?).
Cheers,
Florian

**Comment by 5balls** [comment]
Digging further into the code it is dealing with another kind of user identifiers. Should probably just be documented properly. I will provide a pull request, once I implemented it in my C++ version and understood it.

**Comment by simonjwright** [comment]
It’s seemed to me that the C implementers put in whatever they felt might help their current project without considering whether it was really necessary, and without documenting it, and without sticking to the spirit of LP.

So, I won’t look to implement these "advanced" (read, confusing) features in this project.
