### ISSUE TITLE
Original nuweb limited to 256 scraps?

### ISSUE THREAD

**Issue by 5balls** [simonjwright/nuweb.py#9]
Hello Simon Wright,
I noticed, that you have moved nuweb development to a python rewrite so this question may be obsolete for development. I have however stumbled over one issue with my literate nuweb program. It seems there is a problem with more than 256 scraps (nuweb 1.61). I have not looked deeply into it (just ran a debugger and saw some 256 size array with some bit manipulation where it crashed with a segmentation fault) but can you confirm this limitation? Would you say it is worth hacking around in this part of the code or would the time be better spent on the python version? It seems my nuweb file is not handled well with the python variant yet, maybe scrap argument expansion or something like that.
Thanks and best regards,
Florian Pesth

**Comment by 5balls** [comment]
This seems to fix my problem, at least temporarily. SLAB_SIZE probably does not need to be changed.

```diff
--- nuweb-1.61/scraps.c 2021-10-10 16:50:06.000000000 +0200
+++ nuweb-1.61_modified/scraps.c        2022-04-10 23:46:04.068873951 +0200
@@ -1,5 +1,5 @@
 #include "global.h"
-#define SLAB_SIZE 1024
+#define SLAB_SIZE 2048
 
 typedef struct slab {
   struct slab *next;
@@ -76,6 +76,7 @@
 {
   scraps = 1;
   SCRAP[0] = (ScrapEntry *) arena_getmem(256 * sizeof(ScrapEntry));
+  SCRAP[1] = (ScrapEntry *) arena_getmem(256 * sizeof(ScrapEntry));
 }
 void write_scrap_ref(file, num, first, page)
      FILE *file;
```

**Comment by simonjwright** [comment]
I just had a quick look at it, I’m reminded of why I abandoned the C version (which I’d describe as "illiterate programming", really).
I made a sample with > 300 (identical) scraps, no problems.
Is the problem with the Python version that I don’t support specifying arguments in fragment names?

**Comment by 5balls** [comment]
Thanks for having a look into it. I will have a closer look on both why it breaks on my code and on why the python version does not work on friday or saturday.

**Comment by 5balls** [comment]
I just had another look at it. Unfortunately it seems it is not easy to produce a minimal example which shows the same behaviour as my code. I will try further to provide a minimal example. If you want to test it on my code anyway, commit 5fc21a5 or later in 

https://github.com/5balls/coleitra/tree/0.1-issue-12-grammarprovider-configurable/doc

crashes on my machine (Project coleitra, branch 0.1-issue-12-grammarprovider-configurable). It seems it is only about 255 scraps if I counted right, but there seems to be something different about the type of scraps or the way they are distributed over several files than my recent tests which had more scraps.

**Comment by 5balls** [comment]
> I just had a quick look at it, I’m reminded of why I abandoned the C version (which I’d describe as "illiterate programming", really). I made a sample with > 300 (identical) scraps, no problems. Is the problem with the Python version that I don’t support specifying arguments in fragment names?

Yes, I can't use the python version unfortunately because I specify arguments in fragment names.

**Comment by simonjwright** [comment]
It seems to crash while reading a .aux file (yours has ~530 lines). The code you patched needs more extensive work - try the attached!

—S

**Comment by 5balls** [comment]
Thanks for looking into it again! Unfortunately it seems github ate the attachment. My patch above was indeed just a quick hack, not intended as a pull request / change.

**Comment by simonjwright** [comment]
I managed to get quite confused by this issue being on Github rather than Sourceforge, where the original nuweb is hosted!

I made a change which seems to work OK with your example in the branch [bigger-scraps](https://sourceforge.net/p/nuweb/code/ci/bigger-scraps/tree/) there.

**Comment by 5balls** [comment]
Oh, yes, sorry about that. I've been a bit lazy to create a sourceforge account (which I maybe should, they seem decent again), so I hijacked the Python version.

Thanks a lot for your changes, I can confirm that commit [50c4957](https://sourceforge.net/p/nuweb/code/ci/50c495785542dabc08b56982621ae9a838cff8b0/) in branch [bigger-scraps](https://sourceforge.net/p/nuweb/code/ci/bigger-scraps/tree/) fixes the problem for me.

Hmm, maybe it could throw an error when hitting this limit and offering an command line option to increase this limit? I understand, if you don't want to touch this code again, maybe I will have a look at adding scrap arguments in the python version. Maybe I have some time next week when I am on vacation.

**Comment by simonjwright** [comment]
I’ve made the Sourceforge release 1.62 with this change.

**Comment by 5balls** [comment]
Thanks a lot!
